version: "3"
services:
  service1:
    build: ./node_app/
    ports:
      - 3001:3000
    environment:
      SELF_NAME: "service1"
      NEXT_SERVICE: "service2:3000"
    depends_on:
      - rabbitmq

  service2:
    build: ./groovy_app/
    ports:
      - 3002:3000
    environment:
      SELF_NAME: "service2"
      NEXT_SERVICE: "service3:3000"
    depends_on:
      - rabbitmq

  service3:
    build: ./node_app/
    ports:
      - 3003:3000
    environment:
      SELF_NAME: "service3"
    depends_on:
      - rabbitmq

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    volumes:
      - ./logstash_config/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
      - ./logs/:/logs/
    depends_on:
      - elasticsearch
      - rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - 9200:9200

  rabbitmq:
    image: rabbitmq:3.7
    ports:
      - 5672:5672

  grafana:
    image: grafana/grafana:5.1.3
    ports:
      - 3000:3000

  log_watcher:
    build: ./log_watcher/
    ports:
      - 8000:8000

