version: "3"
services:
  service1:
    build: ./node_app/
    ports:
      - 3001:3000
    environment:
      SELF_NAME: "service1"
      NEXT_SERVICE: "service2:3000"
    depends_on:
      - rabbitmq

  service2:
    build: ./node_app/
    ports:
      - 3002:3000
    environment:
      SELF_NAME: "service2"
      NEXT_SERVICE: "service3:3000"
    depends_on:
      - rabbitmq

  service3:
    build: ./node_app/
    ports:
      - 3003:3000
    environment:
      SELF_NAME: "service3"
      NEXT_SERVICE: "service4:3000"
    depends_on:
      - rabbitmq

  service4:
    build: ./node_app/
    ports:
      - 3004:3000
    environment:
      SELF_NAME: "service4"

    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7
    ports:
      - 5672:5672
